// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  embed: dynamic(() => import("./Embed")),
  top_bar: dynamic(() => import("./TopBar")),
};
